mutation CreateNewCompany($name: String!, $industry: String, $address: String, $phone: String, $website: String) @auth(level: USER) {
  company_insert(data: {
    name: $name,
    industry: $industry,
    address: $address,
    phone: $phone,
    website: $website,
    createdAt_expr: "request.time"
  })
}

query ListAllContacts @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  contacts {
    id
    firstName
    lastName
    email
    phone
    title
    company {
      name
    }
  }
}

mutation UpdateOpportunityStage($id: UUID!, $stage: String!) @auth(level: USER) {
  opportunity_update(
    id: $id,
    data: {
      stage: $stage
    }
  )
}

query ListOpportunitiesByStage($stage: String!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  opportunities(where: { stage: { eq: $stage } }) {
    id
    name
    amount
    expectedCloseDate
    contact {
      firstName
      lastName
    }
    company {
      name
    }
  }
}